export interface Alumno {
  nombre: string;
  apellido: string;
  grado: string;
  notas: {
    nota1: string;
    nota2: string;
    nota3: string;
    nota4: string;
    notaFinal: string;
  };
}
export const alumnos: Alumno[] = [
  {
    nombre: "Juan",
    apellido: "Perez",
    grado: "5",
    notas: {
      nota1: "8",
      nota2: "7",
      nota3: "9",
      nota4: "6",
      notaFinal: "8",
    },
  },
  {
    nombre: "Maria",
    apellido: "Gomez",
    grado: "5",
    notas: {
      nota1: "7",
      nota2: "8",
      nota3: "6",
      nota4: "9",
      notaFinal: "7.5",
    },
  },
  {
    nombre: "Pedro",
    apellido: "Perez",
    grado: "5",
    notas: {
      nota1: "9",
      nota2: "6",
      nota3: "8",
      nota4: "7",
      notaFinal: "8.5",
    },
  },
  {
    nombre: "Felipe",
    apellido: "Paez",
    grado: "5",
    notas: {
      nota1: "6",
      nota2: "9",
      nota3: "7",
      nota4: "8",
      notaFinal: "7.5",
    },
  },
  {
    nombre: "Luis",
    apellido: "Cruz",
    grado: "5",
    notas: {
      nota1: "8",
      nota2: "7",
      nota3: "9",
      nota4: "6",
      notaFinal: "8",
    },
  },
  {
    nombre: "Carlos",
    apellido: "Gomez",
    grado: "5",
    notas: {
      nota1: "7",
      nota2: "8",
      nota3: "6",
      nota4: "9",
      notaFinal: "7.5",
    },
  },
  {
    nombre: "Tomas",
    apellido: "Perez",
    grado: "6",
    notas: {
      nota1: "9",
      nota2: "6",
      nota3: "8",
      nota4: "7",
      notaFinal: "8.5",
    },
  },
  {
    nombre: "Maria",
    apellido: "Jimenez",
    grado: "6",
    notas: {
      nota1: "6",
      nota2: "9",
      nota3: "7",
      nota4: "8",
      notaFinal: "7.5",
    },
  },
  {
    nombre: "Victor",
    apellido: "Pelaez",
    grado: "6",
    notas: {
      nota1: "8",
      nota2: "7",
      nota3: "9",
      nota4: "6",
      notaFinal: "8",
    },
  },
  {
    nombre: "Ulises",
    apellido: "Quintana",
    grado: "6",
    notas: {
      nota1: "7",
      nota2: "8",
      nota3: "6",
      nota4: "9",
      notaFinal: "7.5",
    },
  },
  {
    nombre: "Rafael",
    apellido: "Perez",
    grado: "6",
    notas: { nota1: "7", nota2: "8", nota3: "6", nota4: "9", notaFinal: "7.5" },
  },
  {
    nombre: "Alumno11",
    apellido: "Perez",
    grado: "6",
    notas: { nota1: "9", nota2: "6", nota3: "8", nota4: "7", notaFinal: "8.5" },
  },
  {
    nombre: "Wilmer",
    apellido: "Perez",
    grado: "7",
    notas: { nota1: "6", nota2: "9", nota3: "7", nota4: "8", notaFinal: "7.5" },
  },
  {
    nombre: "Gustavo",
    apellido: "Barrera",
    grado: "7",
    notas: { nota1: "8", nota2: "7", nota3: "9", nota4: "6", notaFinal: "4.5" },
  },
  {
    nombre: "Daniel",
    apellido: "Diaz",
    grado: "7",
    notas: { nota1: "7", nota2: "8", nota3: "6", nota4: "9", notaFinal: "7.5" },
  },
  {
    nombre: "Kevin",
    apellido: "Garcia",
    grado: "8",
    notas: { nota1: "9", nota2: "6", nota3: "8", nota4: "7", notaFinal: "6.5" },
  },
  {
    nombre: "Laura",
    apellido: "Rodriguez",
    grado: "8",
    notas: { nota1: "6", nota2: "9", nota3: "7", nota4: "8", notaFinal: "7.5" },
  },
  {
    nombre: "Brayan",
    apellido: "Perez",
    grado: "8",
    notas: { nota1: "2", nota2: "3", nota3: "4", nota4: "7", notaFinal: "3.5" },
  },
  {
    nombre: "Miguel",
    apellido: "Perez",
    grado: "8",
    notas: { nota1: "7", nota2: "8", nota3: "6", nota4: "9", notaFinal: "7.5" },
  },
  {
    nombre: "David",
    apellido: "Torres",
    grado: "8",
    notas: { nota1: "9", nota2: "6", nota3: "8", nota4: "7", notaFinal: "8.5" },
  },
  {
    nombre: "Jose",
    apellido: "Balboa",
    grado: "8",
    notas: { nota1: "6", nota2: "9", nota3: "7", nota4: "8", notaFinal: "7.5" },
  },
  //   {
  //     nombre: "Alumno21",
  //     grado: "7",
  //     nota1: "8",
  //     nota2: "7",
  //     nota3: "9",
  //     nota4: "6",
  //   },
  //   {
  //     nombre: "Alumno22",
  //     grado: "7",
  //     nota1: "7",
  //     nota2: "8",
  //     nota3: "6",
  //     nota4: "9",
  //   },
  //   {
  //     nombre: "Alumno23",
  //     grado: "7",
  //     nota1: "9",
  //     nota2: "6",
  //     nota3: "8",
  //     nota4: "7",
  //   },
  //   {
  //     nombre: "Alumno24",
  //     grado: "7",
  //     nota1: "6",
  //     nota2: "9",
  //     nota3: "7",
  //     nota4: "8",
  //   },
  //   {
  //     nombre: "Alumno25",
  //     grado: "7",
  //     nota1: "8",
  //     nota2: "7",
  //     nota3: "9",
  //     nota4: "6",
  //   },
  //   {
  //     nombre: "Alumno26",
  //     grado: "7",
  //     nota1: "7",
  //     nota2: "8",
  //     nota3: "6",
  //     nota4: "9",
  //   },
  //   {
  //     nombre: "Alumno27",
  //     grado: "7",
  //     nota1: "9",
  //     nota2: "6",
  //     nota3: "8",
  //     nota4: "7",
  //   },
  //   {
  //     nombre: "Alumno28",
  //     grado: "7",
  //     nota1: "6",
  //     nota2: "9",
  //     nota3: "7",
  //     nota4: "8",
  //   },
  //   {
  //     nombre: "Alumno29",
  //     grado: "7",
  //     nota1: "8",
  //     nota2: "7",
  //     nota3: "9",
  //     nota4: "6",
  //   },
  //   {
  //     nombre: "Alumno30",
  //     grado: "7",
  //     nota1: "7",
  //     nota2: "8",
  //     nota3: "6",
  //     nota4: "9",
  //   },
  //   {
  //     nombre: "Alumno31",
  //     grado: "8",
  //     nota1: "9",
  //     nota2: "6",
  //     nota3: "8",
  //     nota4: "7",
  //   },
  //   {
  //     nombre: "Alumno32",
  //     grado: "8",
  //     nota1: "6",
  //     nota2: "9",
  //     nota3: "7",
  //     nota4: "8",
  //   },
  //   {
  //     nombre: "Alumno33",
  //     grado: "8",
  //     nota1: "8",
  //     nota2: "7",
  //     nota3: "9",
  //     nota4: "6",
  //   },
  //   {
  //     nombre: "Alumno34",
  //     grado: "8",
  //     nota1: "7",
  //     nota2: "8",
  //     nota3: "6",
  //     nota4: "9",
  //   },
  //   {
  //     nombre: "Alumno35",
  //     grado: "8",
  //     nota1: "9",
  //     nota2: "6",
  //     nota3: "8",
  //     nota4: "7",
  //   },
  //   {
  //     nombre: "Alumno36",
  //     grado: "8",
  //     nota1: "6",
  //     nota2: "9",
  //     nota3: "7",
  //     nota4: "8",
  //   },
  //   {
  //     nombre: "Alumno37",
  //     grado: "8",
  //     nota1: "8",
  //     nota2: "7",
  //     nota3: "9",
  //     nota4: "6",
  //   },
  //   {
  //     nombre: "Alumno38",
  //     grado: "8",
  //     nota1: "7",
  //     nota2: "8",
  //     nota3: "6",
  //     nota4: "9",
  //   },
  //   {
  //     nombre: "Alumno39",
  //     grado: "8",
  //     nota1: "9",
  //     nota2: "6",
  //     nota3: "8",
  //     nota4: "7",
  //   },
  //   {
  //     nombre: "Alumno40",
  //     grado: "8",
  //     nota1: "6",
  //     nota2: "9",
  //     nota3: "7",
  //     nota4: "8",
  //   },
  //   {
  //     nombre: "Alumno41",
  //     grado: "9",
  //     nota1: "8",
  //     nota2: "7",
  //     nota3: "9",
  //     nota4: "6",
  //   },
  //   {
  //     nombre: "Alumno42",
  //     grado: "9",
  //     nota1: "7",
  //     nota2: "8",
  //     nota3: "6",
  //     nota4: "9",
  //   },
  //   {
  //     nombre: "Alumno43",
  //     grado: "9",
  //     nota1: "9",
  //     nota2: "6",
  //     nota3: "8",
  //     nota4: "7",
  //   },
  //   {
  //     nombre: "Alumno44",
  //     grado: "9",
  //     nota1: "6",
  //     nota2: "9",
  //     nota3: "7",
  //     nota4: "8",
  //   },
  //   {
  //     nombre: "Alumno45",
  //     grado: "9",
  //     nota1: "8",
  //     nota2: "7",
  //     nota3: "9",
  //     nota4: "6",
  //   },
  //   {
  //     nombre: "Alumno46",
  //     grado: "9",
  //     nota1: "7",
  //     nota2: "8",
  //     nota3: "6",
  //     nota4: "9",
  //   },
  //   {
  //     nombre: "Alumno47",
  //     grado: "9",
  //     nota1: "9",
  //     nota2: "6",
  //     nota3: "8",
  //     nota4: "7",
  //   },
  //   {
  //     nombre: "Alumno48",
  //     grado: "9",
  //     nota1: "6",
  //     nota2: "9",
  //     nota3: "7",
  //     nota4: "8",
  //   },
  //   {
  //     nombre: "Alumno49",
  //     grado: "9",
  //     nota1: "8",
  //     nota2: "7",
  //     nota3: "9",
  //     nota4: "6",
  //   },
  //   {
  //     nombre: "Alumno50",
  //     grado: "9",
  //     nota1: "7",
  //     nota2: "8",
  //     nota3: "6",
  //     nota4: "9",
  //   },
];


